version: "3"
services:
  nginx:
    image: "cra-arc/performance_nginx:latest"
    build:
      context: ../
      dockerfile: docker/performance_nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    container_name: performance_nginx
    volumes:
      - ./performance_nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  web:
    image: "cra-arc/performance_php:latest"
    build:
      context: ../
      dockerfile: docker/performance_php/Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    ports:
      - "9000"
    container_name: performance_web
    volumes:
            - "/js:/var/www/html/js"
